from ..secrets import email as settings, hostname

from smtplib import SMTP
from email.message import EmailMessage

client = SMTP(settings["server"], settings["port"])

def _send(msg):
    client.starttls()
    client.login(settings["user"], settings["password"])
    client.send_message(msg)
    client.quit()

def _send_message(to, template="welcome", **kwargs):
    messages = {
        "welcome": {
            "subject": "Welcome to HT&Me",
            "html": "<div><p>Dear {fullname},</p><p>Thank you for registering to use <strong>HT &amp; Me</p></div>",
            "plain": "Dear {fullname},\n\nThank you for registering to use HT & Me."
        },
        "notify_register": {
            "subject": "A new user has registered for HT&Me",
            "html": """
      <div><p>Dear SWEET Team,</p>
      <p>A user has just registered to the HT&amp;Me website using the code {regcode}.</p>
      <table>
      <p class="smaller">This email was autogenerated by the HT &amp; Me web system</p>
    """,
            "plain": "Dear SWEET Team,\n\nA new user has registered to the HT&Me website using the code {regcode}.\n\nThis email was auto-generated by the HT & Me web system"
        },
        "daily_reminder": {
            "subject": "A reminder to take your hormone therapy",
            "html": "<div><p>Dear {fullname},</p><p>Remember your hormone therapy today.</p><p>From <strong>HT &amp; Me</strong></p></div>",
            "plain": "Dear {fullname}, Remember you hormone therapy today.\n\nFrom HT&Me"
        },
        "monthly_reminder": {
            "subject": "A reminder to order your next hormone therapy prescription",
            "html": "<div><p>Dear {fullname},</p><p>This is a reminder to order your next hormone therapy prescription.</p><p>From <strong>HT &amp; Me</strong></p></div>",
            "plain": "Dear {fullname}, This is a reminder to order your next hormone therapy prescription.\n\nFrom HT&Me"
        },
        "password_reset": {
            "subject": "You have asked to reset your HT&Me password",
            "html": "<div><p>Dear {fullname},</p><p>You are receiving this email because someone has asked to reset your password for HT &amp; Me.</p><p>To reset the password, please visit <a href='https://{hostname}/auth/passwordreset?id={uid}&token={token}'>https://{hostname}/auth/passwordreset?id={uid}&token={token}</a>.</p><p>If you did not request a password reset, please ignore this email.</p></div>",
            "plain": "Dear {fullname}, You are receiving this email because someone has asked to reset your password for HT & Me.\n\nTo reset the password, please visit https://{hostname}/auth/passwordreset?id={uid}&token={token}\n\nIf you did not generate this request, please ignore this email.\n\nFrom HT&Me"
        },
    }

    htmltemplate = """\
<html>
  <head>
    <style>

    </style>
  </head>
  <body>{body}</body>
</html>"""

    msg = EmailMessage()
    msg["To"] = to
    msg["From"] = settings["from"]
    
    msg["Subject"] = messages[template]["subject"].format(**kwargs)
    msg.set_content(messages[template]["plain"].format(**kwargs))
    msg.add_alternative(htmltemplate.format(body=messages[template]["html"].format(**kwargs)), subtype="html")

    _send(msg)

def send_welcome(user):
    fullname = f"{user['firstName']} {user['lastName']}"
    _send_message(f"{fullname} <{user['email']}>", "welcome", fullname=fullname)

def send_notify_register(user):
    _send_message(settings['notify'], "notify_register", regcode=user['userID'])

def email_daily_reminder(user):
    fullname = f"{user['firstName']} {user['lastName']}"
    _send_message(f"{fullname} <{user['email']}>", "daily_reminder", fullname=fullname)

def email_monthly_reminder(user):
    fullname = f"{user['firstName']} {user['lastName']}"
    _send_message(f"{fullname} <{user['email']}>", "monthly_reminder", fullname=fullname)

def send_password_reset(user, token):
    fullname = f"{user['firstName']} {user['lastName']}"
    _send_message(f"{fullname} <{user['email']}>", "password_reset", fullname=fullname, token=token, uid=user['userID'])
