from ..secrets import email as settings

from smtplib import SMTP
from email.message import EmailMessage

client = SMTP(settings["server"], settings["port"])

def _send(msg):
    client.starttls()
    client.login(settings["user"], settings["password"])
    client.send_message(msg)
    client.quit()

def _send_message(to, template="welcome", **kwargs):
    messages = {
        "welcome": {
            "subject": "Welcome to HT&Me",
            "html": "<div><p>Dear {fullname},</p><p>Thank you for registering to use <strong>HT &amp; Me</p></div>",
            "plain": "Dear {fullname},\n\nThank you for registering to use HT & Me."
        },
        "register_notify": {
            "subject": "A new user {fullname} has registered for HT&Me",
            "html": """
      <div><p>Dear SWEET Team,</p>
      <p>A new user has just registered for HT&amp;Me. Their details are as follows:</p>
      <table>
        <tr><td>Registration Code:</td><td>{regcode}</td></tr>
        <tr><td>Full Name:</td><td>{fullname}</td></tr>
        <tr><td>Email Address:</td><td>{email}</td></tr>
      </table>
      <p class="smaller">This email was autogenerated by the HT &amp; Me web system</p>
    """,
            "plain": "Dear SWEET Team,\n\nA new user has registered for HT&Me. Their details are:\n\nRegistration Code: {regcode}\nFull Name: {fullname}\nEmail Address: {email}\n\nThis email was auto-generated by the HT & Me web system"
        }
    }

    htmltemplate = """\
<html>
  <head>
    <style>

    </style>
  </head>
  <body>{body}</body>
</html>"""

    msg = EmailMessage()
    msg["To"] = to
    msg["From"] = settings["from"]
    
    msg["Subject"] = messages[template]["subject"].format(**kwargs)
    msg.set_content(messages[template]["plain"].format(**kwargs))
    msg.add_alternative(htmltemplate.format(body=messages[template]["html"].format(**kwargs)), subtype="html")

    _send(msg)

def send_welcome(user):
    fullname = f"{user['firstName']} {user['lastName']}"
    _send_message(f"{fullname} <user['email']>", "welcome", fullname=fullname)

def send_notify_register(user):
    _send_message(settings['notify'], "notify_register", fullname=f"{user['firstName']} {user['lastName']}", email=user['email'], regcode=user['userID'])