name: Staging Deployment

on:
  push:
    branches:
      - deployment

env:
  AZURE_WEBAPP_NAME: sweetapp # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './SWEET' # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.8'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependencies
      run: |
        sudo apt install python${{ env.PYTHON_VERSION }}-venv
        python -m venv --copies antenv
        source antenv/bin/activate
        pip install setuptools
        pip install -r requirements.txt
    - name: Create Secrets
      run: |
          echo "$SECRETS_FILE" >> SWEET/secrets.py
      shell: bash
      env:
        SECRETS_FILE : ${{secrets.STAGING_ENVS}}
    - name: Building web app
      uses: azure/appservice-build@v2
      with:
        source-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        platform: python
        platform-version: ${{ env.PYTHON_VERSION }}
    - name: Deploy web App using GH Action azure/webapps-deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}